version: '2'

services:

  disconf-data:
    build: .
    image: pzedu/disconf
    networks:
      - lecaishuiinfrastructure_base_network
    volumes:
      - disconf-data-volume:/opt/disconf-rd/war
    command: echo disconf data container
    stdin_open: true
    tty: true
    
  disconf-webapp:
     image: tomcat:7-jre8
     restart: always
     volumes:
       - /dev/./urandom:/dev/random
       - disconf-data-volume:/usr/local/tomcat/webapps/ROOT
     networks:
       lecaishuiinfrastructure_base_network:
         aliases:
           - disconf-webapp
       
networks:
  lecaishuiinfrastructure_base_network:
    external: true
    
volumes:
  disconf-data-volume: