version: '2'

services:
  disconf-data:
    build: .
    image: pzedu/disconf
    volumes:
      - /opt/disconf-rd/war
    command: echo disconf data container
    stdin_open: true
    tty: true
  mysql:
     image: mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: '123456'
     volumes:
       - ./initsql:/docker-entrypoint-initdb.d
  redis:
    image: redis
    restart: always
  zookeeper:
    image: zookeeper
  disconf-webapp:
     image: tomcat:7-jre8
     restart: always
     volumes:
        - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
     volumes_from:
        - disconf-data
     links:
        - disconf-data
        - mysql
        - redis
        - zookeeper
  nginx:
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
    volumes_from:
      - disconf-data
    links:
      - disconf-webapp:disconf-webapp