version: '2'

services:
  disconf-data:
    build: .
    image: pzedu/disconf
    volumes:
      - /opt/disconf-rd/war
    command: echo disconf data container
    stdin_open: true
    tty: true
  disconf-webapp:
     image: tomcat:7-jre8
     restart: always
     volumes:
        - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
     volumes_from:
        - disconf-data
     external_links:
        - lecaishuiinfrastructure_mysql_1:mysql
        - lecaishuiinfrastructure_redis_1:redis
        - lecaishuiinfrastructure_zookeeper_1:zookeeper