version: '2'

services:

  nginx:
    image: nginx
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /pzedu/doc:/pzedu/doc
      - dockerdisconf_disconf-data-volume:/opt/disconf-rd/war
    ports:
      - "80:80"
    restart: always
    networks:
      - lecaishuiinfrastructure_base_network
      
networks:
  lecaishuiinfrastructure_base_network:
    external: true
    
volumes:
  dockerdisconf_disconf-data-volume:
    external: true