version: '3'
services:
  registry:
    image: registry:2
    volumes:
      - registry-data:/var/lib/registry
    tty: true
    stdin_open: true

  nginx-registry-proxy:
    image: nginx
    ports:
      - 443:443
    depends_on:
      - registry
    tty: true
    stdin_open: true 
    
volumes:
  registry-data: