nginx-registry-proxy:
  image: registry.lecaishui.com/nginx-registry-proxy
  ports:
    - 443:443
  links:  
    - registry:registry
  tty: true
  stdin_open: true 
registry:
  image: registry.lecaishui.com/registry
  tty: true
  stdin_open: true