version: '2'

services:
  jenkins:
    image : jenkins
    restart: always
    ports:
      - "6180:8080"
    volumes:
      - /pzedu/data/jenkins:/var/jenkins_home
      - ./conf/jenkins/log.properties:/var/jenkins_home/log.properties
    environment:
      - "JAVA_OPTS:-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
    networks:
      - lecaishuiinfrastructure_base_network

  #docker hub link for image https://hub.docker.com/r/blacklabelops/jira/
  jira:
    image: blacklabelops/jira
    restart: always
    ports:
      - '6181:8080'
    volumes:
      - /pzedu/data/jira:/var/atlassian/jira
      - ./conf/jira/atlassian-extras-3.2.jar:/opt/jira/atlassian-jira/WEB-INF/lib/atlassian-extras-3.2.jar
    environment:
      - 'JIRA_DATABASE_URL=mysql://jiraadmin@mysql/jiradb'
      - 'JIRA_DB_PASSWORD=jiraadmin'
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
      #nginx proxy
#      - 'JIRA_PROXY_NAME='
#      - 'JIRA_PROXY_PORT='
#      - 'JIRA_PROXY_SCHEME='
      - 'DOCKER_WAIT_HOST=mysql'
      - 'DOCKER_WAIT_PORT=3306'
    networks:
      - lecaishuiinfrastructure_base_network
  solr:
    build: ./solr
    restart: always
    port:
      - "6182:8983"
    volumes:
      - "/pzedu/data/solr/*:/opt/solr/server/solr/*"
      - "./conf/solr:/opt/solr/server/solr/lib"
      
networks:
  lecaishuiinfrastructure_base_network:
    external: true