version: '3'
services:
  zoo1:
    image: zookeeper:3.4.10
    hostname: zoo1
    restart: always
    ports:
      - 2181:2181
    networks:
      - zoo-net  
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    deploy:
      placement:
        constraints:
          - node.labels.name == infrastructure-service
  
  zoo2:
    image: zookeeper:3.4.10
    hostname: zoo2
    restart: always
    ports:
      - 2182:2181
    networks:
      - zoo-net      
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    deploy:
      placement:
        constraints:
          - node.labels.name == infrastructure-service 
  
  zoo3:
    image: zookeeper:3.4.10
    hostname: zoo3
    restart: always
    ports:
      - 2183:2181
    networks:
      - zoo-net
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    deploy:
      placement:
        constraints:
          - node.labels.name == infrastructure-service      
networks:
  zoo-net: