version: '3'
services:
  zoo1:
    image: registry.lecaishui.com/zookeeper:3.3.6
    hostname: zoo1
    networks:
      - zook-net  
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  
  zoo2:
    image: registry.lecaishui.com/zookeeper:3.3.6
    hostname: zoo2
    networks:
      - zook-net      
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  
  zoo3:
    image: registry.lecaishui.com/zookeeper:3.3.6
    hostname: zoo3
    networks:
      - zook-net
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
networks:
  zook-net: